### ISSUE TITLE
Register MSIT

### ISSUE THREAD

**Issue by Rashi1997** [brown-ccv/task-registry-data#1]
**Instructions**
Fill in the below yml template as per the specification in the comments.
You can view the preview side-by-side for the yml below you are editing and see changes reflected in real-time as you edit.
```yml
taskName: MSIT Task                            # [String, required]
links: 
  deployment: https://msit.com                 # [String::URL, optional]
  sourceCode: https://github.com/msit/task     # [String::URL, required]
  publication: https://msit.com                # [String::URL, optional]
framework:
  library:                                        # [Array::String, optional]
    
    
  language:                                       # [Array::String, optional]
    
lab:
  name: Lab name                                          # [String, required]
  institution: Brown University                          # [String, required]
  principalInvestigator:                          # [String, optional]
  developers:                                     # [Array::String, optional]
    
  website: 
platform:                                         # [Boolean, optional]
  desktop:
    windows: false
    linux: false
    mac: false
  mobile:
    ios: false
    android: false
features:                                         # [Boolean, optional]
  electron: false
  browser: false
  docker: false
  eegTrigger: false
  mturk: false
tags:                                             # [Array::String, optional]
  - tag
```
