### ISSUE TITLE
Register Effort Task

### ISSUE THREAD

**Issue by wasita** [brown-ccv/task-registry-data#13]
**Instructions**
Fill in the below yml template as per the specification in the comments.
You can view the preview side-by-side for the yml below you are editing and see changes reflected in real-time as you edit.
```yml
taskName: Effort Task                           # [String, required]
links: 
  deployment: 'https://task-effort.web.app/'                 # [String::URL, optional]
  sourceCode: 'https://github.com/lnccbrown/task-effort'     # [String::URL, required]
  publication:              # [String::URL, optional]
framework:
  library:                                        # [Array::String, optional]
    - jsPsych 
    - React
  language:                                       # [Array::String, optional]
    - JavaScript
lab:
  name: LNCC                                           # [String, required]
  institution: Brown University                                    # [String, required]
  principalInvestigator: Michael J Frank                         # [String, optional]
  developers:                                     # [Array::String, optional]
    - Wasita Mahaphanit
    - Rashi Dhar
  website: 'https://lnccbrown.com'                   # [String::URL, optional]
platform:                                         # [Boolean, optional]
  desktop:
    windows: true
    linux: true
    mac: true
  mobile:
    ios: false
    android: false
features:                                         # [Boolean, optional]
  electron: true
  browser: true
  docker: false
  eegTrigger: true
  mturk: true
  psiturk: true
  firebase: true
  prolific: true
tags:                                             # [Array::String, optional]
  - balloon effort task
  - decision making
  - effort

```
