### ISSUE TITLE
Testing edits on issue

### ISSUE THREAD

**Issue by Rashi1997** [brown-ccv/task-registry-data#15]
**Instructions**
Fill in the below yml template as per the specification in the comments.
You can view the preview side-by-side for the yml below you are editing and see changes reflected in real-time as you edit.
```yml
# YML template does not require Strings and Boolean to be in quotes, also URL.
taskName: edits to issue testing 2                          # [String, required] 
links: 
  deployment: https://test.com                 # [String::URL, optional]
  sourceCode: https://github.com/test/task     # [String::URL, required]
  publication: https://test.com                # [String::URL, optional]
framework:
  library:                                        # [Array::String, optional]
    - test 
    - test
  language:                                       # [Array::String, optional]
    - test
    - test
lab:
  name:                     test                      # [String, required]
  institution:            test                        # [String, required]
  principalInvestigator:                          # [String, optional]
  developers:                                     # [Array::String, optional]
    - DEVELOPER_1
    - DEVELOPER_2
  website: https://example.com                    # [String::URL, optional]
platform:                                         # [Boolean, optional]
  desktop:
    windows: false
    linux: false
    mac: false
  mobile:
    ios: false
    android: false
features:                                         # [Boolean, optional]
  electron: false
  browser: false
  docker: false
  eegTrigger: false
  mturk: false
tags:                                             # [Array::String, optional]
  - test
```
