### ISSUE TITLE
Register Provocation

### ISSUE THREAD

**Issue by Rashi1997** [brown-ccv/task-registry-data#28]
**Instructions**
Fill in the below yml template as per the specification in the comments.
You can view the preview side-by-side for the yml below you are editing and see changes reflected in real-time as you edit.
```yml
# YML template does not require Strings(also URL) and Boolean to be in quotes.
# Please add a valid URL starting with https.
taskName: Provocation Task                            # [String, required] 
about: 
  description: 'Rate distress from 0-10 in response to neutral or provoking images'    # [String, required]
  deployment:                 # [String::URL, optional]
  sourceCode: 
    access: private                     # [String, required] Stating if the GitHub repository is private or public.
    link:        # [String::URL, optional] If the repository is public, provide URL.
  publication:               # [String::URL, optional]
framework:
  - name: neuro-task-starter                             # [Array::String, optional]
    link: https://github.com/brown-ccv/neuro-task-starter                     # [String::URL, optional] 
language:                                         # [Array::String, optional]
  - javascript
lab:                                              # List of the labs who collaborated.
  - name:  Borton                                         # [String, required]
    institution: Brown University                                   # [String, required]
    principalInvestigator: David Borton                         # [String, optional]
    developers:                                     # [Array::String, optional]
      - Nicole Provenza
    website: http://borton.engin.brown.edu/                # [String::URL, optional]
  - name:  CCV                                         # [String, required]
    institution: Brown University                                   # [String, required]
    principalInvestigator:                          # [String, optional]
    developers:                                     # [Array::String, optional]
      - Fernando Gelin
      - Mary McGrath
    website: https://ccv.brown.edu               # [String::URL, optional]
platform:                                         # [Boolean, optional]
  desktop:
    windows: true
    linux: true
    mac: true
  mobile:
    ios: false
    android: false
features:                                         # [Boolean, optional]
  electron: true
  browser: false
  docker: false
  eegTrigger: true
  mturk: true
tags:                                             # [Array::String, optional]
  - provocation
  - OCD
  - distress
```
