### ISSUE TITLE
Register PURL

### ISSUE THREAD

**Issue by wasita** [brown-ccv/task-registry-data#41]
**Instructions**
Fill in the below yml template as per the specification in the comments.
You can view the preview side-by-side for the yml below you are editing and see changes reflected in real-time as you edit.
```yml
# YML template does not require Strings(also URL) and Boolean to be in quotes.
# Please add a valid URL starting with https.
taskName: PURL                           # [String, required] 
about: 
  description: Perceptual unertainty reward (or reinforcement) learning (PURL) task. 1st part is a learning and decision making task. 2nd part is a surprise recall/episodic memory test. Involves perceptual category ambiguous stimuli.   # [String, required]
  deployment:                 # [String::URL, optional]
  sourceCode: 
    access: private                       # [String, required] Stating if the GitHub repository is private or public.
    link: https://github.com/lnccbrown/perceptual-uncertainty-mturk-task         # [String::URL, optional] If the repository is public, provide URL.
  publication:                # [String::URL, optional]
framework:
  - name: jsPsych                             # [Array::String, optional]
    link: https://www.jspsych.org                     # [String::URL, required] 
language:                                         # [Array::String, optional]
  - JavaScript
lab:                                              # List of the labs who collaborated.
  - name: LNCC                                          # [String, required]
    institution: Brown University                                   # [String, required]
    principalInvestigator: Michael J Frank                          # [String, optional]
    developers:                                     # [Array::String, optional]
      - Wasita Mahaphanit
      - Andra Geana
    website: https://lnccbrown.com                    # [String::URL, optional]
platform:                                         # [Boolean, optional]
  desktop:
    windows: true
    linux: true
    mac: true
  mobile:
    ios: false
    android: false
features:                                         # [Boolean, optional]
  electron: false
  browser: true
  docker: false
  eegTrigger: false
  mturk: true
tags:                                             # [Array::String, optional]
  - learning
  - decision making
  - memory
  - perceptual uncertainty
```
