### ISSUE TITLE
Register Effort

### ISSUE THREAD

**Issue by Rashi1997** [brown-ccv/task-registry-data#7]
**Instructions**
Fill in the below yml template as per the specification in the comments.
You can view the preview side-by-side for the yml below you are editing and see changes reflected in real-time as you edit.
```yml
taskName: Effort Task                            # [String, required]
links: 
  deployment: https://effort.com                 # [String::URL, optional]
  sourceCode: https://github.com/effort/task     # [String::URL, required]
  publication:                 # [String::URL, optional]
framework:
  library:                                        # [Array::String, optional]
    - react 
    - jspsych
  language:                                       # [Array::String, optional]
    - javascript
    - python
lab:
  name:      Lab Name                                     # [String, required]
  institution:        Brown University                            # [String, required]
  principalInvestigator:                          # [String, optional]
  developers:                                     # [Array::String, optional]
    - dev1
    - dev2
  website:                    # [String::URL, optional]
platform:                                         # [Boolean, optional]
  desktop:
    windows: false
    linux: false
    mac: false
  mobile:
    ios: false
    android: false
features:                                         # [Boolean, optional]
  electron: false
  browser: false
  docker: false
  eegTrigger: false
  mturk: false
tags:                                             # [Array::String, optional]
  - t1
  - t2
  - t3
```
